#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "lBWEb/ZPG0o5"
#define LAYER_STATE_8BIT

#define TAPPING_TERM 250
#define QUICK_TAP_TERM 100
#define FLOW_TAP_TERM 150
#define PERMISSIVE_HOLD
#define CHORDAL_HOLD
#define SPECULATIVE_HOLD

#define RGB_MATRIX_STARTUP_SPD 60
