#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "Xx4y9/MaRGxK"
#define LAYER_STATE_8BIT
#define VOYAGER_USER_LEDS

#define TAPPING_TERM 250
#define QUICK_TAP_TERM 100
#define FLOW_TAP_TERM 100
#define PERMISSIVE_HOLD
#define CHORDAL_HOLD
#define SPECULATIVE_HOLD
#define DUMMY_MOD_NEUTRALIZER_KEYCODE KC_F18
#define MODS_TO_NEUTRALIZE { MOD_BIT(KC_LEFT_ALT), MOD_BIT(KC_RIGHT_ALT), MOD_BIT(KC_LEFT_GUI), MOD_BIT(KC_RIGHT_GUI) }

#define SELECT_WORD_OS_MAC
#define CYCLOTAB_KEYS LCMD(KC_TAB)

#define NAVIGATOR_SCROLL_DIVIDER 50
#define NAVIGATOR_SCROLL_INVERT_X
#define NAVIGATOR_SCROLL_INVERT_Y
#define NAVIGATOR_TRACKBALL_CPI_TICK 10
#define AUTOMOUSE_LAYER 5
#define AUTOMOUSE_TIMEOUT 5000
#define AUTOMOUSE_THRESHOLD 30
#define AUTOMOUSE_SCROLL_THRESHOLD AUTOMOUSE_THRESHOLD / NAVIGATOR_SCROLL_DIVIDER

#define RGB_MATRIX_STARTUP_SPD 60
